// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcqQmbN3x7W677QLrDtL53p5UWVEGcR04',
    appId: '1:455545752969:web:81293ca310751ae90ea558',
    messagingSenderId: '455545752969',
    projectId: 'in-stock-tracker-59cba',
    authDomain: 'in-stock-tracker-59cba.firebaseapp.com',
    storageBucket: 'in-stock-tracker-59cba.appspot.com',
    measurementId: 'G-PR97FETJRG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD28rZaZCMRj5lTmjR_ET5JImQsNllLMvo',
    appId: '1:455545752969:android:9df024020b5e22940ea558',
    messagingSenderId: '455545752969',
    projectId: 'in-stock-tracker-59cba',
    storageBucket: 'in-stock-tracker-59cba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoSXp_v6bSLZv-Egm6L1CRall_LaG46dY',
    appId: '1:455545752969:ios:c0d03c4235d598210ea558',
    messagingSenderId: '455545752969',
    projectId: 'in-stock-tracker-59cba',
    storageBucket: 'in-stock-tracker-59cba.appspot.com',
    iosClientId: '455545752969-cltpng4gr48ggiidpe5l8tdltcvaui2k.apps.googleusercontent.com',
    iosBundleId: 'potato.inStockTrackerNew',
  );
}
